services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    ports:
      - '${DEV_POSTGRES_PORT}:5432'
    volumes:
      - dev_pg_data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:latest
    container_name: postgres-test
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    ports:
      - '${TEST_POSTGRES_PORT}:5432'
    volumes:
      - test_pg_data:/var/lib/postgresql/data

volumes:
  dev_pg_data:
  test_pg_data:
